- name: install dotnet 7.0 server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: extract microsoft package
      ansible.builtin.get_url:
        dest: /tmp
        url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        mode: '777'
    - name: package
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb
        state: "present"
    - name: install dotnet-sdk-7.0
      ansible.builtin.apt:
        name: dotnet-sdk-7.0
        state: latest
        update_cache : true