- name: install dotnet 6.0 on ubuntu
  hosts: all
  become: yes
  vars:
    dotnet_version: "6.0"
  tasks: 
    - name: install dotnet 6.0
      ansible.builtin.apt: 
        name: dotnet-sdk-"{{ dotnet_version }}"
        state: latest
        update_cache : true
--- 

- name: install dotnet 6.0 on ubuntu
  hosts: all
  become: yes
  vars:
    dotnet_version: "dotnet-sdk-6.0"
  tasks: 
    - name: install dotnet
      ansible.builtin.apt: 
        name: "{{ dotnet_version }}"
        state: latest
        update_cache : true