        
- name: install dotnet 7.0 server on centos
  hosts: all
  become: yes
  tasks:
    - name: extract microsoft package
      ansible.builtin.get_url:
        dest: /tmp
        url: https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
        mode: '777'
    - name: package
      ansible.builtin.yum:
        name: /tmp/packages-microsoft-prod.rpm
        state: "present"
    - name: install dotnet-sdk-7.0
      ansible.builtin.yum:
        name: dotnet-sdk-7.0
        state: latest
