- name: install apache server on ubuntu and php
  hosts: all
  become: yes
  tasks: 
    - name: install apache2
      ansible.builtin.apt: 
        name: apache2
        state: latest
        update_cache : true
    - name: install php
      ansible.builtin.apt: 
        name:  
          - php
          - libapache2-mod-php 
          - php-mysql
        state: latest
        update_cache: true 
    - name: copy the file
      ansible.builtin.copy:
        dest: /var/www/html/info.php
        content: 
          - <?php phpinfo(); ?>
        remote_src: true
    - name: start the service
      ansible.builtin.systemd:
        name: apache2
        enabled: true
        state: started 